[appearance]
theme_day = "ocean"
theme_night = "ocean"
font = "serif"
font_size = "XL"

[header.navbar]
enable = true
align = "l"
show_logo = true
show_language = false
show_day_night = true
show_search = false
highlight_active_link = true

[locale]
date_format = "2006-01-02"
time_format = "15:04"
address_format = "en-gb"

[features.syntax_highlighter]
theme_light = "github-light"
theme_dark = "dracula"

[features.math]
enable = false

[features.privacy_pack]
enable = false

[features.avatar]
gravatar = false
shape = "circle"

[extensions.academicons]
enable = true

[security]
allow_frame = true
